### ISSUE TITLE
Reduce size of dependabot.yml configuration

### ISSUE THREAD

**Issue by OptimumCode** [bowtie-json-schema/bowtie#1834]
The dependabot's configuration allows defining multiple directories for a single ecosystem (e.g. pip, npm, etc). This can be achieved by using `directories` property instead of `directory`. The documentation for that option can be found [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--).

**Comment by Julian** [comment]
This probably slightly complicates the [pre-commit hook ensuring all implementations appear in the file](https://github.com/bowtie-json-schema/bowtie/blob/main/.pre-commit-hooks/check-dependabot).

Which is to say -- I'm fine with reviewing a PR to use that syntax of course, but given it makes some other thing harder, I don't see gigantic benefit in moving (and it may make this harder for a first issue).

**Comment by OptimumCode** [comment]
I see now, thank you for pointing that out. I did not notice that check.

According to the documentation, the new property `directories` supports wildcards

> The directories key supports globbing and the wildcard character

Maybe, we could create something like this for every ecosystem:

```yaml
  - package-ecosystem: "docker"
    directories:
    - "/implementations/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directories:
    - "/implementations/*"
    schedule:
      interval: "daily"
```

and will make sure, all implementations are included.
